### ISSUE TITLE
can't add blank line in yaml

### ISSUE THREAD

**Issue by l2eused** [beaussan/update-time-on-edit-obsidian#64]
I can't add any blank line in yaml while this plugin is enable. when I try to add blank line in yaml, in few sec later it will delete that line.

Is this problem can fix? because

- to improve user style (I want to add blank line for each yaml. also before and after horizontal bar)
- may break some another plugin (e.g linter)
- I don't think it necessary to have this behavior

**Comment by DynamicPlayerSector** [comment]
This and #56 happens because the plugin uses Obsidian's API to modify metadata since 2.0.0. [That's how it's intended to work](https://github.com/obsidianmd/obsidian-api/issues/110#issuecomment-1500356605). I used to use this plugin, but after the update, I didn't like this behavior either, so I created a new plugin myself which has a way with dealing with metadata without using Obsidian's API. It's called Time Things. You can try it by [installing manually from my repo](https://github.com/DynamicPlayerSector/timethings), or waiting until it comes to the community plugin list. You can use it until Obsidian's team solves this, or @beaussan comes up with a fix. Keep in mind that my plugin is not a replacement to this plugin, because it doesn't have some functionality that may be important for you, like excluding folders, yet.
