### ISSUE TITLE
Improving control of the "created" field

### ISSUE THREAD

**Issue by autonomygaps** [beaussan/update-time-on-edit-obsidian#8]
This plugin has the potential to be enormously useful, particularly in collaborative contexts (as a kind of versioning).  But the "created" field introduces some real problems. What currently makes the plugin unusable for me is that existing notes, some of which were created years ago, are given the "created on" date of the first date on which it is modified.

Please: it would be great, for now, to be able to include only the "updated" date, and nothing about a creation date, at least until it can reflect the actual creation date.

**Comment by beaussan** [comment]
Thank you !

Yes, the created field is tricky. I can't really rely on the created time by obsidian / file system because if the sync is done without obsidian (eg git), the created time will be wrong.

Adding a flag to disable the created flag could be a workaround indeed.

A futur version could introduce the ability for the user to choose if the created time should be based by the file system, obsidian created time or now (actual behavior), with the posiblity to disable it all together.

**Comment by beaussan** [comment]
Should be fixed by https://github.com/beaussan/update-time-on-edit-obsidian/releases/tag/1.1.0, I will open (or feel free to so so) another issue about how to get the created time

**Comment by autonomygaps** [comment]
Thanks so much for already doing this!
> A future version could introduce the ability for the user to choose if the created time should be based by the file system, obsidian created time or now (actual behavior), with the possibility to disable it altogether.

By the way, the Dataview plugin provides an easy way to see what the actual created date is for the current file, which can then be copy-and-pasted into the YAML metadata (you need to add the three back-ticks at the start and end, but they don't show up here).  Perhaps this could be a basis for a revised "created time" function? 

````
dataview
LIST dateformat(file.ctime, "yyyy-mm-dd")
WHERE file.name = this.file.name
````
